### ISSUE TITLE
Add support for PX4 flight modes

### ISSUE THREAD

**Issue by thedevleon** [TobiasBales/PlayuavOSD#13]
Running the PlayUAVOSD with a PX4 I do mostly get correct data to be displayed, but sadly the flight mode display just says "Unknown". 
Could you add PX4 flight modes please :)?

Bascially, PX4 sends it's flight mode in a custom data format `px4_custom_mode` via the custom_mode variable in the mavlink heartbeat message.

For more info, see [how it's sent](https://github.com/PX4/Firmware/blob/f3ee22b22c75593620d13af8d97fbbe1a35d3cff/src/modules/mavlink/mavlink_messages.cpp#L133) and [how it's encoded](https://github.com/PX4/Firmware/blob/2f48317a9ea7b05d8c61b3d1c44f8229491350b1/src/modules/commander/px4_custom_mode.h).

**Comment by TobiasBales** [comment]
I will take a look if it is easy to integrate using the current mavlink library,
will report back (if I don't forget ;))

**Comment by thedevleon** [comment]
Did you take a look? I would implement it myself, but I fried my osd :(

**Comment by thedevleon** [comment]
@TobiasBales please :D?

**Comment by thedevleon** [comment]
@TobiasBales Just got my replacement OSD and managed to test everything and confirm it works.
See my PR #18

**Comment by TobiasBales** [comment]
Thanks for that, will look into it later today!

**Comment by StewLG** [comment]
Since we've merged the relevant changes in PR #18, and thedevleon seems happy with them, I'm closing this issue.
