### ISSUE TITLE
Compiled hex?

### ISSUE THREAD

**Issue by athertop** [TobiasBales/PlayuavOSD#14]
Tobias, I don't do coding using Arm and so don't have the toolset installed. Is there any chance you could provide a compiled version with your release files? Thanks, Paul A

**Comment by TobiasBales** [comment]
There is a link in the readme, see https://github.com/TobiasBales/PlayuavOSD#build ;)

I will be adding auto downloading/detecting of new versions at some point not too far away,
then there will be no need for manual fiddling with hex files anymore.

**Comment by athertop** [comment]
Good man! Thanks Tobi.
