### ISSUE TITLE
Intermittent issue with Altimeter displaying wildly wrong values

### ISSUE THREAD

**Issue by StewLG** [TobiasBales/PlayuavOSD#23]
https://vimeo.com/183227708/4ab9609c49

This is run from a compile of master as of about 9-15-2016.

And yes, I did check the source log file from ArduPlane. It looks fine:

![barodatawasfineinflightcontroller](https://cloud.githubusercontent.com/assets/7128339/18619385/833ed774-7daf-11e6-916d-6ea45849a3b7.png)

**Comment by athertop** [comment]
Looks like the home distance also is off. Where you landed - how far is this from where you acquired GPS fix?

**Comment by StewLG** [comment]
Good observation - I agree the home distance looks very off.

Landing point:    47.50974, -121.8009
Home point:       47.50897, -121.7994  

This diagram is an accurate illustration of where I started and landed. The Drotek GPS had 16 sats with an HDOP of 0.7 - 0.8, and should be very precise for this flight. Google Earth has the distance from landing point to home as 140 meters:

![landingdistanceoffby40meters](https://cloud.githubusercontent.com/assets/7128339/18736571/268c2a28-803d-11e6-9bd7-7a4e3ddca7fb.png)

The PlayUAV code claims I am 185 meters from home after coming to a stop:

![185_meters_to_home](https://cloud.githubusercontent.com/assets/7128339/18736665/07053ea0-803e-11e6-910c-5030b009c871.png)

The 40 meter difference is a long way to be off (almost 30%), and it's a pretty clear-cut calculation, no? No ellipsoidal/spherical/great circle issues here.

**Comment by StewLG** [comment]
I believe I've come up with a fix for the broken distance algorithm, as well as the home arrow:

Beta firmware to try:

https://github.com/StewLG/catfood/blob/master/PlayUavOSD-FixedDistanceAndBearing-SLG-09-24-2016.zip

More details:

http://fpvlab.com/forums/showthread.php?40658-A-Graphics-OSD-for-APM-Pixhawk&p=812912&viewfull=1#post812912

**Comment by StewLG** [comment]
I am reasonably confident the home direction/distance issues have been corrected; see the following links for more information:

https://github.com/TobiasBales/PlayuavOSD/commit/1354059b41e643bdcfe8ae7142c3ee8b050657fc
https://github.com/TobiasBales/PlayuavOSD/issues/19
http://en.playuav.com/question/6

As for the altimeter displaying wildly wrong values, I am encouraged that I have not had any problems - or heard reports of any problems - since this commit:

https://github.com/TobiasBales/PlayuavOSD/commit/648937dc923ba5dda9be73bf5a2a9ca7282bb4bc

I am NOT certain this has corrected the problem, but I'm hopefully enough to close this issue for the moment.
