### ISSUE TITLE
Add Filter to Vario

### ISSUE THREAD

**Issue by trgFPV** [TobiasBales/PlayuavOSD#8]
At the moment the numerical vario is almost useless because the output is to noisy. (Values fluctuate strongly even if the plane is on the ground) Some kind of Filter should help

**Comment by TobiasBales** [comment]
That is why I started with the vario graph but that might not be enough/a catch all options.
Ideas welcome :D

**Comment by trgFPV** [comment]
I think implementing a moving average Filter would be a good starting point: https://en.wikipedia.org/wiki/Moving_average_%28finance%29 I think that would already do the trick
